CREATE TABLE veiculo(
matricula int GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1),
capacidade int not null,
latitude int not null,
longitude int not null,
tipo boolean not null,
primary key(matricula)
)